Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -13,18 +13,24 @@ jobs:
     steps:
       - name: "Test"
         run: |
-          if [ jq --help &> /dev/null ] && [[ "true" == "true" ]]; then
-            echo "::notice:: Helm release ship-9999-backend exists, skipping service create"
-          else
-            set +e
-            exitcode=1
-  
-            # fetch container logs
-  
-            if [ $exitcode -ne 0 ]; then
-              echo "::error::Helm release ship-9999-backend failed! Check migration and application logs for startup errors."
-            fi
+          set +e
+          jq --help &> /dev/null
+          exists=$?
 
-            exit $exitcode
+          # skip service upgrade if "replace" is not enabled
+          if [ $exists -eq 0 ] && [ "true" == "true" ]; then
+            echo "::notice:: Helm release ship-9999-backend exists, skipping service create"
+            exit 0
           fi
-  
+
+          # perform upgrade
+          exitcode=1
+
+          # fetch container logs
+          
+          # check for failures
+          if [ $exitcode -ne 0 ]; then
+            echo "::error::Helm release ship-9999-backend failed! Check migration and application logs for startup errors."
+          fi
+
+          exit $exitcode
