Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -12,7 +12,17 @@ jobs:
       Greeting: test
     steps:
       - name: "Test"
-        run: echo $Greeting $First_Name ${{ env.TEST }}
-        env:
-          First_Name: $Greeting-${TEST}
+        run: |
+          if true && [ "true" != "true" ]; then
+            echo "::notice:: Helm release ship-9999-backend exists, skipping service create"
+          else
+            set +e
+            exitcode=1
+          
+            # fetch container logs
+            
+            if [ $exitcode -ne 0 ]; then echo "::error::Helm release ship-9999-backend failed! Check migration and application logs for startup errors." fi
+          
+            exit $exitcode
+          fi;
   
